sudo: required
env:
  global:
    CC_TEST_REPORTER_ID=74f243d61252d77cceed36b21a35163c95b404527e746c983c155602aed25e55

addons:
  chrome: stable

language: node_js
node_js:
  - '8.11.3'

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run build-libs
  - ng test ng-sq-common
  - ng test ng-datatable
  - ng test ng-datetime-picker
  - ng test ng-sq-ui
  - ng test ng-modal

after_success:
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
